# ========================================
# HB Jekyll 主题配置文件
# 网站基本设置
# ========================================

# 网站信息
title: HB ☺                              # 网站标题
description: Notes，Posts，Microblog，HbW.Me  # 网站描述
baseurl: "/hbblog"                         # 子路径，如 /blog
url: "https://hellopages.github.io"      # 网站完整URL

# 作者信息
author:
  name: "HB"                             # 作者姓名
  email: "hello@hbw.me"                  # 作者邮箱
  bio: "一个热爱技术的开发者"              # 作者简介

# 构建设置
markdown: kramdown                       # Markdown 解析器
highlighter: rouge                       # 代码高亮器
permalink: /:categories/:year/:month/:day/:title/  # 文章URL格式

# 分页设置 
  paginate: 5                 # 首页每页显示文章数
paginate_path: "/page:num/"   # 首页分页URL格式

# 外部CSS
# external_css:
#  - "https://hbw.me/blog/assets/css/style.css"

# 分类页面分页设置 - 为各个分类页面添加独立的分页配置
category_pagination:
  notes:
    per_page: 4                          # Notes每页显示5篇文章
    path: "/notes/page:num/"             # Notes分页URL格式
  posts:
    per_page: 6                          # Posts每页显示5篇文章
    path: "/posts/page:num/"             # Posts分页URL格式
  microblog:
    per_page: 6                          # Microblog每页显示5篇文章
    path: "/microblog/page:num/"         # Microblog分页URL格式

# 首页显示设置
home_display:
  notes_count: 3                        # 首页显示Notes数量
  posts_count: 3                        # 首页显示Posts数量
  microblog_count: 3                    # 首页显示Microblog数量

# 插件配置
plugins:
  - jekyll-feed                         # RSS订阅插件 (开启/关闭: 注释此行)
  - jekyll-seo-tag                      # SEO优化插件 (开启/关闭: 注释此行)
# - jekyll-paginate                    # 分页插件 (开启/关闭: 注释此行)
  - jekyll-sitemap                      # 网站地图插件 (开启/关闭: 注释此行)
  - jekyll-paginate-v2                  # 高级分页插件，支持多分页

# 主题特性开关
theme_settings:
  # 功能开关
  features:
    dark_mode: true                     # 是否启用暗黑模式切换
    search: true                        # 是否启用搜索功能
    comments: true                      # 是否启用评论功能
    social_share: true                  # 是否启用社交分享
    
  # 导航菜单
  navigation:
    - title: "首页"
      url: "/"
    - title: "Notes"
      url: "/notes"
    - title: "Posts" 
      url: "/posts"
    - title: "Microblog"
      url: "/microblog"
    - title: "归档"
      url: "/archive"
    - title: "标签"
      url: "/tags"
    - title: "关于"
      url: "/about"

  # 评论系统配置
  comments:
    provider: "utterances"              # 评论提供商: utterances, disqus
    utterances:
      repo: "username/repository"       # GitHub仓库
      issue-term: "pathname"            # 问题标识方式
      theme: "github-light"             # 主题: github-light, github-dark
    disqus:
      shortname: "your-disqus-shortname" # Disqus短名称

  # 社交媒体链接
  social:
    twitter: "https://twitter.com/username"
    github: "https://github.com/username"
    email: "mailto:hello@example.com"

# 页面设置
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE

# 包含页面目录
include:
  - _pages
